### ISSUE TITLE
Broken models in 1.18.10 and up

### ISSUE THREAD

**Issue by StickyChannel92** [Arexon/furnideco#24]
![image](https://user-images.githubusercontent.com/48563620/151623770-11ef3979-405f-4275-8c9f-8aefbf78cc7e.png)

**Comment by Arexon** [comment]
Yeah, I'm aware about this bug. It's due to new changes with the add-on API. Will put this on the task board for v1.2.0

**Comment by StickyChannel92** [comment]
I also noticed when I toggled on the global pack for Furnideco, all Marketplace skins, skin packs and skin parts are gone, except for uploaded skins.

**Comment by Arexon** [comment]
That's because FurniDeco uses custom player animations for sitting, which disables the Character Creator skins
