### ISSUE TITLE
Realm mod adding causes Gamemode one sonic behavior pack to be added

### ISSUE THREAD

**Issue by TwistedRainbow** [Arexon/furnideco#28]
adding furnideco+geometry fix to a realm forces the realm to make you download the Gamemode one sonic simply explained

**Comment by Arexon** [comment]
I suppose because Geometry Fix uses the sonic map UUID to bypass the recent geometry limitation, Minecraft thinks it's the map's resources pack and therefor downloads the content. Are you sure this is limited to Realms only? Do worlds have this issue too?

**Comment by TwistedRainbow** [comment]
no, this a realm specific issue as this bug was attempted by me and a friend's realm

**Comment by Arexon** [comment]
Since it's Realm-specific I can't fix it. You could try opening a bug report on the official bug tracker for Minecraft, but because Geometry Fix is more of a "workaround" it might not work
